# Generated by Django 4.1.2 on 2022-11-05 16:00

import brokentv.web.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), brokentv.web.validators.validator_profile_username])),
                ('bio', models.CharField(blank=True, max_length=240, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(2), brokentv.web.validators.validator_profile_name_only_letters])),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(2), brokentv.web.validators.validator_profile_name_only_letters])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
