# Generated by Django 4.1.2 on 2022-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_user_profile_image.png', upload_to='profile/'),
        ),
    ]
